### ISSUE TITLE
Consulta foto

### ISSUE THREAD

**Issue by bcochon** [pdepjm/2024-tp0-presentacion-JuanchiNogueira#2]
Amigo millo muy buena foto. Sos de ir mucho a la cancha? Vas siempre a la Belgrano? Me entró curiosidad, saludos

**Comment by JuanchiNogueira** [comment]
Buenas, si suelo ir bastante pero normalmente a centenario baja, justo ese dia no habia asi que toco belgrano alta jajajaj saludos
